# Generated by Django 4.2.20 on 2025-05-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_lote"),
        ("administraddor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merma",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.producto"
            ),
        ),
    ]
