# Generated by Django 4.2.20 on 2025-05-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administraddor", "0002_alter_merma_producto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
