# Generated by Django 4.2.20 on 2025-05-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administraddor", "0003_delete_producto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merma",
            name="lote",
        ),
    ]
