# Generated by Django 4.2.20 on 2025-05-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administraddor", "0004_remove_merma_lote"),
    ]

    operations = [
        migrations.AddField(
            model_name="merma",
            name="lote_codigo",
            field=models.CharField(default="L-000", max_length=20),
            preserve_default=False,
        ),
    ]
