# Generated by Django 4.2.20 on 2025-05-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administraddor", "0005_merma_lote_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merma",
            old_name="lote_codigo",
            new_name="lote",
        ),
    ]
