# Generated by Django 4.2.20 on 2025-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("tipo", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
