# Generated by Django 4.2.20 on 2025-05-13 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="fecha",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="lote",
            field=models.CharField(default="Sin lote", max_length=50),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(),
        ),
    ]
