# Generated by Django 4.2.20 on 2025-05-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_producto_fecha_producto_lote_producto_precio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="lote",
        ),
    ]
