# Generated by Django 4.2.20 on 2025-05-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_producto_lote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("total_productos", models.PositiveIntegerField()),
                ("fecha_ingreso", models.DateField()),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
    ]
