# Generated by Django 4.2.20 on 2025-05-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_lote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lote",
            old_name="fecha_ingreso",
            new_name="fecha",
        ),
        migrations.RenameField(
            model_name="lote",
            old_name="nombre",
            new_name="numero",
        ),
        migrations.RemoveField(
            model_name="lote",
            name="total_productos",
        ),
        migrations.AddField(
            model_name="lote",
            name="producto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.producto",
            ),
            preserve_default=False,
        ),
    ]
