# Generated by Django 4.2.20 on 2025-05-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_fecha_ingreso_lote_fecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="lote_numero",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
