# Generated by Django 5.1.2 on 2025-05-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
