# Generated by Django 5.1.2 on 2025-05-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('lista', 'Lista'), ('cancelada', 'Cancelada')], default='registrada', max_length=20),
        ),
    ]
