# Generated by Django 5.1.2 on 2025-05-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_compra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lote_numero', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='registration.producto'),
        ),
    ]
