# Generated by Django 5.1.2 on 2025-05-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_detallecompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Lista', 'Lista'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
