# Generated by Django 5.1.2 on 2025-06-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_compra_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.CreateModel(
            name='ProductoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('unidad', 'Unidad'), ('caja', 'Caja')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='registration.producto')),
            ],
            options={
                'unique_together': {('producto', 'unidad_medida')},
            },
        ),
    ]
