# Generated by Django 5.1.2 on 2025-06-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_remove_producto_cantidad_remove_producto_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallelote',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detallelote',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallelote',
            name='producto_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.productounidad'),
        ),
    ]
