# Generated by Django 5.1.2 on 2025-06-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_remove_detallelote_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='numero',
        ),
    ]
