# Generated by Django 5.1.2 on 2025-06-14 21:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_remove_lote_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merma',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='merma',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='merma',
            name='producto',
        ),
        migrations.AddField(
            model_name='merma',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merma',
            name='producto_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='registration.productounidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merma',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='merma',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas', to='registration.lote'),
        ),
        migrations.AlterField(
            model_name='merma',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
