# Generated by Django 5.1.2 on 2025-06-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_productounidad_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.productounidad'),
            preserve_default=False,
        ),
    ]
