# Generated by Django 5.1.2 on 2025-06-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_venta_activo_venta_estado_venta_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='observaciones',
        ),
    ]
