# Generated by Django 5.1.2 on 2025-06-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_remove_detalleventa_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=20),
        ),
    ]
