# Generated by Django 5.1.2 on 2025-06-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_venta_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
    ]
