# Generated by Django 5.1.2 on 2025-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Fruta', 'Fruta'), ('Verdura', 'Verdura'), ('Otro', 'Otro')], max_length=20),
        ),
    ]
