# Generated by Django 5.1.2 on 2025-06-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_cliente_descuento_aplicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='descuento_aplicado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contador_cupon',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
